#!/usr/bin/env bash

set -e

JJS_PACK_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
UC="unsigned char"
U8="uint8_t"
LICENSE=$(cat <<EOF
/* Copyright Light Source Software, LLC and other contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
EOF
)

function cleanup {
  rm -f "${JJS_PACK_DIR}/min.snapshot" "${JJS_PACK_DIR}/min.js"
}

trap cleanup EXIT

function gen {
  PACK="$1"
  PACK_JS="$2"
  echo "Generating ${PACK}..."

  esbuild --bundle "${JJS_PACK_DIR}/${PACK}/${PACK_JS}.js" --minify --format=cjs --outfile="${JJS_PACK_DIR}/min.js"

  jjs-snapshot generate -f "module,exports" -o "${JJS_PACK_DIR}/min.snapshot" "${JJS_PACK_DIR}/min.js"

  SNAPSHOT=$(xxd -i -n "jjs_pack_${PACK_JS//-/_}_snapshot" "${JJS_PACK_DIR}/min.snapshot")
  SNAPSHOT="${SNAPSHOT//$UC/$U8}"
  SNAPSHOT="#if JJS_SNAPSHOT_EXEC\n${SNAPSHOT}\n#else /* !JJS_SNAPSHOT_EXEC */"

  MIN=$(xxd -i -n "jjs_pack_${PACK_JS//-/_}_min_js" "${JJS_PACK_DIR}/min.js")
  MIN="${MIN//$UC/const $U8}"
  MIN="${MIN}\n#endif /* JJS_SNAPSHOT_EXEC */"

  OUT="${JJS_PACK_DIR}/${PACK}/jjs-pack-${PACK_JS}-js.c"

  echo -e "${LICENSE}" > "${OUT}"
  echo -e "\n/* Generated by gen-pack-js.sh */\n#include <stdint.h>\n\n${SNAPSHOT}\n${MIN}" >> "${OUT}"
}

gen console console
gen domexception domexception
gen path path
gen performance performance
gen url url
gen url url-search-params
