#!/usr/bin/env bash

set -e

JJS_PACK_DIR=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
LICENSE=$(cat <<EOF
/* Copyright Light Source Software, LLC and other contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
EOF
)

function cleanup {
  rm -f "${JJS_PACK_DIR}/min.snapshot" "${JJS_PACK_DIR}/min.js"
}

trap cleanup EXIT

function gen {
  PACK="$1"
  PACK_JS="$2"
  IDENT=$(echo "JJS_PACK_${1}" | tr '[:lower:]' '[:upper:]' | tr - _)

  echo "Generating ${PACK}..."

  esbuild --bundle "${JJS_PACK_DIR}/${PACK}/${PACK_JS}.js" --minify --format=cjs --outfile="${JJS_PACK_DIR}/min.js"

  jjs-snapshot generate -f "module,exports" -o "${JJS_PACK_DIR}/min.snapshot" "${JJS_PACK_DIR}/min.js"

  SNAPSHOT=$(xxd -i -n "jjs_pack_${PACK_JS//-/_}_snapshot" "${JJS_PACK_DIR}/min.snapshot")

  OUT="${JJS_PACK_DIR}/${PACK}/jjs-pack-${PACK_JS}-js.c"

  echo -e "${LICENSE}" > "${OUT}"
  echo -e "\n/* Generated by gen-pack-js.sh */\n\n#include \"jjs-pack-config.h\"\n\n#if ${IDENT}\n#include <stdint.h>\n\n${SNAPSHOT}\n#endif /* ${IDENT} */\n" >> "${OUT}"

  # note: snapshot bytes need to be writable!
  U8REGEX="s/unsigned char/uint8_t/g"
  U32REGEX="s/unsigned int/const uint32_t/g"

  # note: sed is orders of magnitude faster than bash variable replacement
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i "" "${U8REGEX}" "${OUT}"
    sed -i "" "${U32REGEX}" "${OUT}"
  else
    sed -i "${U8REGEX}" "${OUT}"
    sed -i "${U32REGEX}" "${OUT}"
  fi
}

gen console console
gen domexception domexception
gen fs fs
gen path path
gen performance performance
gen text text-api
gen url url-api
