set(CMAKE_SYSTEM_NAME "${CMAKE_HOST_SYSTEM_NAME}")
set(CMAKE_SYSTEM_PROCESSOR "${CMAKE_HOST_SYSTEM_PROCESSOR}")

if (CMAKE_HOST_WIN32)
    set(ZIG_WRAPPER_EXT ".cmd")
else()
    set(ZIG_WRAPPER_EXT ".sh")
endif()

set(CMAKE_C_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/zig-cc${ZIG_WRAPPER_EXT}")
set(CMAKE_CXX_COMPILER "${CMAKE_CURRENT_LIST_DIR}/bin/zig-c++${ZIG_WRAPPER_EXT}")
set(CMAKE_AR "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ar${ZIG_WRAPPER_EXT}")
set(CMAKE_C_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ar${ZIG_WRAPPER_EXT}")
set(CMAKE_CXX_COMPILER_AR "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ar${ZIG_WRAPPER_EXT}")
set(CMAKE_RANLIB "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ranlib${ZIG_WRAPPER_EXT}")
set(CMAKE_C_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ranlib${ZIG_WRAPPER_EXT}")
set(CMAKE_CXX_COMPILER_RANLIB "${CMAKE_CURRENT_LIST_DIR}/bin/zig-ranlib${ZIG_WRAPPER_EXT}")
set(ZIG_CROSS_COMPILING ON)

#add_compile_definitions(
#    _POSIX_C_SOURCE=200112L
#)

if (CMAKE_HOST_APPLE)
    set(CMAKE_OSX_SYSROOT "")
endif()
