name: jjs CI

#on: [push, pull_request]
on: workflow_dispatch

env:
  CMAKE_GENERATOR: Ninja
  RUNNER: tools/run-tests.py
  ASAN_OPTIONS: detect_stack_use_after_return=1:check_initialization_order=true:strict_init_order=true
  JJS_ASAN_BUILD_OPTS_32: --buildoptions=--cpointer-32bit=off,--error-messages=off,--line-info=off,--mem-heap=512,--stack-limit=0,--compile-flag=-fsanitize=address,--compile-flag=-fno-omit-frame-pointer,--compile-flag=-fno-common,--compile-flag=-O2,--system-allocator=on,--linker-flag=-fuse-ld=gold,--compile-flag=-m32
  JJS_ASAN_BUILD_OPTS_64: --buildoptions=--cpointer-32bit=off,--error-messages=off,--line-info=off,--mem-heap=512,--stack-limit=0,--compile-flag=-fsanitize=address,--compile-flag=-fno-omit-frame-pointer,--compile-flag=-fno-common,--compile-flag=-O2,--system-allocator=off,--linker-flag=-fuse-ld=gold
  JJS_ASAN_SKIP_LIST: --skip-list=parser-oom.js,parser-oom2.js,stack-limit.js,regression-test-issue-4901.js,regression-test-issue-4848.js,regression-test-issue-4890.js,regression-test-issue-2190.js,regression-test-issue-2258-2963.js,regression-test-issue-2448.js,regression-test-issue-2905.js,regression-test-issue-3785.js,proxy-evil-recursion.js
  UBSAN_OPTIONS: print_stacktrace=1
  JJS_UBSAN_BUILD_OPTS_32: --buildoptions=--cpointer-32bit=off,--error-messages=off,--line-info=off,--mem-heap=512,--stack-limit=0,--compile-flag=-fsanitize=undefined,--compile-flag=-fno-omit-frame-pointer,--compile-flag=-fno-common,--linker-flag=-fuse-ld=gold,--cpointer-32bit=on,--external-context=on,--compile-flag=-m32
  JJS_UBSAN_BUILD_OPTS_64: --buildoptions=--cpointer-32bit=off,--error-messages=off,--line-info=off,--mem-heap=512,--stack-limit=0,--compile-flag=-fsanitize=undefined,--compile-flag=-fno-omit-frame-pointer,--compile-flag=-fno-common,--linker-flag=-fuse-ld=gold,--cpointer-32bit=on,--external-context=on
  JJS_UBSAN_SKIP_LIST: --skip-list=stack-limit.js,regression-test-issue-4901.js,regression-test-issue-4890.js,regression-test-issue-4848.js,regression-test-issue-3785.js,regression-test-issue-2905.js,regression-test-issue-2448.js,regression-test-issue-2258-2963.js,proxy-evil-recursion.js,regression-test-issue-2190.js

jobs:
  Checks:
    if: false # XXX: checks only work on 18.04, but github has deprecated the runner
    runs-on: ubuntu-18.04 # needed for checker version stability
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: sudo apt update
      - run: sudo apt install doxygen clang-format-10 cppcheck pylint python3-serial
      - run: $RUNNER --check-signed-off=gh-actions
        if: ${{ always() }}
      - run: $RUNNER --check-doxygen
        if: ${{ always() }}
      - run: $RUNNER --check-format
        if: ${{ always() }}
      - run: $RUNNER --check-license
        if: ${{ always() }}
      - run: $RUNNER --check-strings
        if: ${{ always() }}
      - run: $RUNNER --check-pylint
        if: ${{ always() }}
      - run: $RUNNER --check-cppcheck
        if: ${{ always() }}

  linux_x86-64_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests
      - run: $RUNNER -q --jjs-pack-tests
      - run: $RUNNER -q --unittests

  linux_x86-64_debug:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests --build-debug
      - run: $RUNNER -q --jjs-pack-tests --build-debug
      - run: $RUNNER -q --unittests --build-debug

  linux_x86-64_buildopts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: sudo apt update
      - run: sudo apt install gcc-multilib
      - run: $RUNNER --buildoption-test

  linux_x86_release_asan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-multilib ninja-build
      - run: $RUNNER -q --jjs-tests $JJS_ASAN_BUILD_OPTS_32 $JJS_ASAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests $JJS_ASAN_BUILD_OPTS_32 $JJS_ASAN_SKIP_LIST

  linux_x86_debug_asan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-multilib ninja-build
      - run: $RUNNER -q --jjs-tests --build-debug $JJS_ASAN_BUILD_OPTS_32 $JJS_ASAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests --build-debug $JJS_ASAN_BUILD_OPTS_32 $JJS_ASAN_SKIP_LIST

  linux_x86-64_release_asan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests $JJS_ASAN_BUILD_OPTS_64 $JJS_ASAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests $JJS_ASAN_BUILD_OPTS_64 $JJS_ASAN_SKIP_LIST

  linux_x86-64_debug_asan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests --build-debug $JJS_ASAN_BUILD_OPTS_64 $JJS_ASAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests --build-debug $JJS_ASAN_BUILD_OPTS_64 $JJS_ASAN_SKIP_LIST

  linux_x86_release_ubsan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-multilib ninja-build
      - run: $RUNNER -q --jjs-tests $JJS_UBSAN_BUILD_OPTS_32 $JJS_UBSAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests $JJS_UBSAN_BUILD_OPTS_32 $JJS_UBSAN_SKIP_LIST

  linux_x86_debug_ubsan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-multilib ninja-build
      - run: $RUNNER -q --jjs-tests --build-debug $JJS_UBSAN_BUILD_OPTS_32 $JJS_UBSAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests --build-debug $JJS_UBSAN_BUILD_OPTS_32 $JJS_UBSAN_SKIP_LIST

  linux_x86-64_release_ubsan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests $JJS_UBSAN_BUILD_OPTS_64 $JJS_UBSAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests $JJS_UBSAN_BUILD_OPTS_64 $JJS_UBSAN_SKIP_LIST

  linux_x86-64_debug_ubsan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install ninja-build
      - run: $RUNNER -q --jjs-tests --build-debug $JJS_UBSAN_BUILD_OPTS_64 $JJS_UBSAN_SKIP_LIST
      - run: $RUNNER -q --jjs-pack-tests --build-debug $JJS_UBSAN_BUILD_OPTS_64 $JJS_UBSAN_SKIP_LIST

  linux_armv6l_release:
    if: false # needs raspberry pi cross compiler to be set up
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-arm-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --buildoptions=--toolchain=cmake/toolchain_linux_armv6l.cmake,--linker-flag=-static
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user-static
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  linux_armv6l_debug:
    if: false # some unit tests fail on 32 bit debug builds
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-arm-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --build-debug --buildoptions=--toolchain=cmake/toolchain_linux_armv6l.cmake,--linker-flag=-static
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user-static
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  linux_armv7l_release:
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-arm-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --buildoptions=--toolchain=cmake/toolchain_linux_armv7l.cmake,--linker-flag=-static
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user-static ninja-build
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-pack-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  linux_armv7l_debug:
    # note: external-context + stack_limit > 0 are broken on 32 bit debug builds
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-arm-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --build-debug --buildoptions=--toolchain=cmake/toolchain_linux_armv7l.cmake,--linker-flag=-static
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-arm-linux-gnueabihf libc6-dev-armhf-cross qemu-user-static ninja-build
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests --no-external-context-tests
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-pack-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  linux_aarch64_release:
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-aarch64-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --buildoptions=--toolchain=cmake/toolchain_linux_aarch64.cmake,--linker-flag=-static
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-aarch64-linux-gnu libc6-dev-armhf-cross qemu-user-static ninja-build
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-pack-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  linux_aarch64_debug:
    runs-on: ubuntu-22.04
    env:
      RUNTIME: qemu-aarch64-static
      TIMEOUT: 300
      JJS_BUILD_OPTS: -q --buildoptions=--toolchain=cmake/toolchain_linux_aarch64.cmake,--linker-flag=-static --build-debug
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install gcc-aarch64-linux-gnu libc6-dev-armhf-cross qemu-user-static ninja-build
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-tests
      - run: $RUNNER $JJS_BUILD_OPTS --jjs-pack-tests
      - run: $RUNNER $JJS_BUILD_OPTS --unittests

  macos_x86-64_release:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: brew install ninja
      - run: python $RUNNER -q --jjs-tests
      - run: python $RUNNER -q --jjs-pack-tests
      - run: python $RUNNER -q --unittests

  macos_x86-64_debug:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: brew install ninja
      - run: python $RUNNER -q --jjs-tests --build-debug
      - run: python $RUNNER -q --jjs-pack-tests --build-debug
      - run: python $RUNNER -q --unittests --build-debug

  windows_x64_release:
    # note: Date().getDay() is broken on windows, disable associated tests
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - run: Remove-Variable -name CMAKE_GENERATOR
        shell: powershell
      - name: JS Tests
        run: python .\tools\run-tests.py -q --jjs-tests --skip-list=regression-test-issue-1386.js,date-setters.js
        shell: powershell
      - name: Pack(age) Unit Tests
        run: python .\tools\run-tests.py -q --jjs-pack-tests
        shell: powershell
      - name: C Unit Tests
        run: python .\tools\run-tests.py -q --unittests
        shell: powershell

  windows_x64_debug:
    # note: Date().getDay() is broken on windows, disable associated tests
    # note: external-context + stack_limit > 0 are broken on windows debug builds (problem seen in linux 32 bit also)
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - run: Remove-Variable -name CMAKE_GENERATOR
        shell: powershell
      - name: JS Tests
        run: python .\tools\run-tests.py -q --build-debug --jjs-tests --skip-list=regression-test-issue-1386.js,date-setters.js --no-external-context-tests
        shell: powershell
      - name: Pack(age) Unit Tests
        run: python .\tools\run-tests.py -q --build-debug --jjs-pack-tests
        shell: powershell
      - name: C Unit Tests
        run: python .\tools\run-tests.py -q --build-debug --unittests
        shell: powershell

  ecma_test262_release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: python $RUNNER --test262
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test262-report-release
          path: |
            build/tests/test262/local/bin/test262.report

  ecma_test262_debug:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: python $RUNNER --test262 --build-debug
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Test262-report-debug
          path: |
            build/tests/test262-debug/local/bin/test262.report

  zig_example:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2.2.0
        with:
          version: 0.11.0
      - run: python tools/build.py --amalgam ON
      - run: cd zig/example && zig build run
