name: release

on: workflow_dispatch

env:
  CREATOR: ./tools/ci-create-release-bundle.sh

jobs:
  linux-x86:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install gcc-multilib
      - run: $CREATOR linux-x86 tgz --compile-flag=-m32 --linker-flag=-static
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-linux-x86
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  linux-x64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: $CREATOR linux-x64 tgz --linker-flag=-static
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-linux-x64
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  linux-armv7l:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install gcc-arm-linux-gnueabihf
      - run: $CREATOR linux-armv7l tgz --toolchain=cmake/toolchain_linux_armv7l.cmake --linker-flag=-static
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-linux-armv7l
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  linux-aarch64:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu
      - run: $CREATOR linux-aarch64 tgz --toolchain=cmake/toolchain_linux_aarch64.cmake --linker-flag=-static
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-linux-aarch64
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  macos-x64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - run: $CREATOR macos-x64 tgz
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-macos-x64
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  macos-arm64:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - run: $CREATOR arm64-x64 tgz --compile-flag=-arch arm64
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-macos-arm64
          path: |
            build/jjs-*.tgz
            build/jjs-*.rev
  windows-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - run: $CREATOR windows-x64 zip
        shell: bash
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-windows-x64
          path: |
            build/jjs-*.zip
            build/jjs-*.rev
  amalgam:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: ./tools/build.py --amalgam ON --jjs-pack ON
      - run: cd build && tar -czf amalgam.tgz amalgam && zip -r amalgam.zip amalgam
      - uses: actions/upload-artifact@v4
        if: success()
        with:
          name: jjs-amalgam
          path: |
            build/amalgam.tgz
            build/amalgam.zip
